### ISSUE TITLE
Bonfire needs to declare its dependency on setuptools

### ISSUE THREAD

**Issue by awood** [RedHatInsights/bonfire#359] opened 2024-04-03 20:43 UTC
After upgrading from F38 to F39, I bumped into the following

```
Traceback (most recent call last):                                                                        
  File "/home/awood/devel/rhsm-subscriptions/.venv/bin/bonfire", line 5, in <module>                      
    from bonfire.bonfire import main_with_handler                                                         
  File "/home/awood/devel/rhsm-subscriptions/.venv/lib/python3.12/site-packages/bonfire/bonfire.py", line 
14, in <module>                                                                                           
    import bonfire.config as conf                                                                         
  File "/home/awood/devel/rhsm-subscriptions/.venv/lib/python3.12/site-packages/bonfire/config.py", line 8
, in <module>                                                                                             
    from pkg_resources import resource_filename                                                           
ModuleNotFoundError: No module named 'pkg_resources'   
```

I did a `pip install -U setuptools` which fixed the problem, but I think `bonfire` needs to declare `setuptools` as a runtime dependency under 'project` rather that just a `build-system` dependency.

**Comment by Victoremepunto** [comment] 2024-08-05 16:25
duplicate of #365

**Closed by Victoremepunto** 2024-08-05 16:25 UTC
