### ISSUE TITLE
Bonfire doesn't work with oc 4.17

### ISSUE THREAD

**Issue by psegedy** [RedHatInsights/bonfire#431] opened 2024-10-15 16:52 UTC
```
2024-10-15 18:42:13 [   ERROR] [          MainThread] hit fatal error: 'oc process' command failed: error: failed to read input object (not a Template?): unable to decode "STDIN": no kind "Template" is registered for version "v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
```

```
oc version
Client Version: 4.17.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Kubernetes Version: v1.29.8+632b078
```

it works fine with older version downloaded directly from the cluster
```
oc version
Client Version: 4.16.0-202410011135.p0.gc44c839.assembly.stream.el9-c44c839
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Kubernetes Version: v1.29.8+632b078
```

however homebrew has only the latest version of `oc` which is not compatible with bonfire

**Comment by bsquizz** [comment] 2024-10-18 20:33
I think this is the root cause of your problem: https://github.com/opendevstack/ods-quickstarters/issues/639

Try changing your template to use `apiVersion: template.openshift.io/v1` and see if that works.

**Comment by bsquizz** [comment] 2024-12-03 19:14
This was fixed via https://github.com/RedHatInsights/ocviapy/pull/13

**Closed** 2024-12-03 19:15 UTC
